[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops-course-labs"
version = "0.1.0"

[tool.setuptools]
packages = ["MLOps_Course_Labs"]  # Use underscore naming