name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_NAME: churn-prediction
  TAG: ${{ github.sha }}  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        PYTHONPATH=. pip install -e .
    
    - name: Run pytest
      run: |
        python -m pytest src/tests/test_api.py -v

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}  

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} .

    - name: Tag and Push to ECR
      run: |
        FULL_IMAGE_NAME="${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
        docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} $FULL_IMAGE_NAME
        docker push $FULL_IMAGE_NAME
        echo "ECR_IMAGE=$FULL_IMAGE_NAME" >> $GITHUB_ENV

    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no \
            -i ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        # Create personal directory
        mkdir -p ~/mazen-app
        cd ~/mazen-app
        
        # Clone or update repo
        if [ -d "MLOps-Course-Labs" ]; then
            cd MLOps-Course-Labs
            git pull
        else
            git clone https://github.com/${{ github.repository }}.git
            cd MLOps-Course-Labs
        fi
        
        # Login to ECR
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
        
        # Update and deploy
        sed -i "s|image:.*|image: $ECR_IMAGE|" docker-compose.yml
        docker-compose down || true
        docker-compose pull
        docker-compose up -d
        
        # Add identification
        echo "Deployed by Mazen on $(date)" > deployment-info.txt
EOF
        echo "Deployment completed on EC2 instance."